name: "Coverage"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          verbose: true # optional (default = false)

