name: Publish docs

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          config_file: .jsdoc.rc
          front_page: README.md
      
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          # The regular expression (or fixed string) we want to replace
          find: '<!--SPONSOR-->'
          # The new string to replace with
          replace: '<script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?serve=CEAIC5QJ&placement=arjunkomathgithubio" id="_carbonads_js"></script>'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
